import Head from "next/head"
import React from "react"

const Meta = () => {
  return (
    <Head>
      <title>Farm Finder | Greenshield </title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.png" />
    </Head>
  )
}

export default Meta
